version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    # Group packages into shared PRs
    groups:
      lint:
        patterns:
          - '@eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'globals'
          - 'prettier'
          - 'typescript-eslint'
          - '@typescript-eslint/*'

