name: Code style checks

on: pull_request

jobs:
  lint:
    name: Code style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      # npm v11.12.0 fails to install packages from GitHub.
      # Ref https://github.com/npm/cli/issues/9133
      # TODO: Revert the version constraint to "latest" after the issue is resolved.
      - name: Update npm
        run: npm install --global npm@'<11.12.0'
      - name: Install dependencies
        run: npm ci
      - name: Run code style checks
        run: npm run lint
